#!/bin/bash
set -euo pipefail

# Helper for adding Git HTTPS credentials to the libsecret keyring
#
# Note: You need `git-credential-libsecret' somewhere in your PATH.

credentials_form() {
	zenity \
		--forms \
		--separator=$'\n' \
		--title "Store Git HTTPS Credentials" \
		--add-entry="Host (e.g. github.com)" \
		--add-entry=Username \
		--add-password=Password
}

store_with_helper() {
	read -r DOMAIN
	test -n "${DOMAIN}" || return 1

	read -r USERNAME
	test -n "${USERNAME}" || return 1

	read -r PASSWORD
	test -n "${PASSWORD}" || return 1

	git-credential-libsecret store >/dev/null <<EOF
protocol=https
host=${DOMAIN}
username=${USERNAME}
password=${PASSWORD}
EOF
}

if credentials_form | store_with_helper
then
	exec seahorse
else
	zenity --error --text "Failed to store credentials"
fi

