#!/bin/bash
set -eu

# Helper for adding Git HTTPS credentials to the libsecret keyring
#
# Note: You need `git-credential-libsecret' somewhere in your PATH.

credentials_form() {
	zenity \
		--forms \
		--separator=$'\n' \
		--title "Store Git HTTPS Credentials" \
		--add-entry="Host (e.g. github.com)" \
		--add-entry=Username \
		--add-password=Password
}

store_with_helper() {
	read -r DOMAIN
	test -n "${DOMAIN:-}"

	read -r USERNAME
	test -n "${USERNAME:-}"

	read -r PASSWORD
	test -n "${PASSWORD:-}"

	git-credential-libsecret store >/dev/null <<EOF
protocol=https
host=${DOMAIN}
username=${USERNAME}
password=${PASSWORD}
EOF
}

clean_tmp() {
	unlink "$TMP" 2>/dev/null || true
}

TMP=$(mktemp -t git-credential-libsecret-add-https.XXXXXX)
trap clean_tmp INT TERM HUP QUIT EXIT

if credentials_form >"$TMP"
then
	if store_with_helper <"$TMP"
	then
		exec seahorse
	else
		zenity --error --text "Failed to store credentials"
	fi
fi

